version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  fastify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
